### PR TITLE
remove auth0 reference and split id on pipe

### PR DESCRIPTION
**Pull request by kutoft**
Handles cases where user ID from Auth0 will have different designators depending on which social sign on method they used.  
Auth0 = auth0|...
Github = github|...

etc.

### CODE REVIEW

**Review by jhodak — DISMISSED** [review]

**Comment by jhodak** [comment]
The only thought I have is that...split is definitely a point of failure if for some reason a user does not have a pipe |...I think they always will with auth0.  

But we could have a function that gets used everywhere that is just...
if (/\|/.test(str)) {
 str.split('|')[1]
} else {
str
}

**Review by carlosvq — APPROVED** [review]

**Comment by commoddity** [comment]
Similar to what @jhodak said: the only improvement I'd suggest would be moving the split/formatting logic to a utility function and then using that function everywhere. But not a big deal, code works as is.

In terms of the split logic itself, I believe that so long as users are always coming from Auth0 they will always follow the format `string|userId` so it should be fine but redundancy never hurts either.

**Comment by kutoft** [comment]
> Similar to what @jhodak said: the only improvement I'd suggest would be moving the split/formatting logic to a utility function and then using that function everywhere. But not a big deal, code works as is.
> 
> In terms of the split logic itself, I believe that so long as users are always coming from Auth0 they will always follow the format `string|userId` so it should be fine but redundancy never hurts either.

Ill make the change

**Comment by kutoft** [comment]
@jhodak @commoddity can you guys take another look?

**Comment by commoddity** [comment]
LGTM

**Review by commoddity — APPROVED** [review]
Approved.

**Comment by jhodak** [comment]
LGTM - At least now if we run into any problems, we have only one spot to add or edit our logic to get the user appropriately.

**Pull request merged**
