### PR TITLE
remove old verify logic and simplify flow

### PR DESCRIPTION
**Pull request by kutoft**
- remove old verify logic that was talking to mongodb
- simply verify flow

todo:
- get copy from gabi

### CODE REVIEW

**Review by jhodak — DISMISSED** [review]
LGTM overall.  I think there is an env variable imported in login but now unnecessary getting flagged as a warning.  Otherwise significantly simpler and much shorter.

**Review by jhodak — APPROVED** [review]
LGTM

**Comment by kutoft** [comment]
Link T-10943

**Comment by kutoft** [comment]
Close T-10943

**Pull request merged**
